<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>EfCore.EncryptedProperties.Samples.AzuriteBlobs</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EfCore.EncryptedProperties\EfCore.EncryptedProperties.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.28.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.16" />
  </ItemGroup>

</Project>
