<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EfCore.EncryptedProperties.Testing</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EfCore.EncryptedProperties\EfCore.EncryptedProperties.csproj" />
  </ItemGroup>

</Project>
